<?php

namespace Database\Seeders;

use App\Models\tb_aset;
use Illuminate\Database\Seeder;

class AsetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $aset = [
            [
                'kd_aset' => 'AST-00001',
                'nama' => 'Rumah',
                'tgl_perolehan' => '2016-03-31',
                'cabang_id' => '1',
                'penempatan_id' => '1',
                'spek' => 'Tanah dan Bangunan SHM no.0258/Mekarrahayu dan no.02541/Mekarrahayu',
                'qty' => '2',
                'umur_ekonomis_id' => '1',
                'kondisi_id' => '2',
                'harga' => '76128000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00002',
                'nama' => 'AC 1PK',
                'tgl_perolehan' => '2013-11-23',
                'cabang_id' => '3',
                'penempatan_id' => '1',
                'spek' => 'samsung/z-pipe05/putih',
                'qty' => '2',
                'umur_ekonomis_id' => '3',
                'kondisi_id' => '4',
                'harga' => '2500000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00003',
                'nama' => 'AC 1,5PK',
                'tgl_perolehan' => '2013-09-2',
                'cabang_id' => '2',
                'penempatan_id' => '10',
                'spek' => 'Mitsubishi Electric',
                'qty' => '1',
                'umur_ekonomis_id' => '3',
                'kondisi_id' => '2',
                'harga' => '3400000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00004',
                'nama' => 'AC 2PK',
                'tgl_perolehan' => '2014-10-12',
                'cabang_id' => '5',
                'penempatan_id' => '20',
                'spek' => 'Panasonic - 2PK',
                'qty' => '2',
                'umur_ekonomis_id' => '3',
                'kondisi_id' => '2',
                'harga' => '6700000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00005',
                'nama' => 'Mesin Hitung Uang',
                'tgl_perolehan' => '2015-8-9',
                'cabang_id' => '8',
                'penempatan_id' => '11',
                'spek' => 'Casio-DR140TM',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '3750000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00006',
                'nama' => 'Mesin FAX',
                'tgl_perolehan' => '2014-03-30',
                'cabang_id' => '9',
                'penempatan_id' => '11',
                'spek' => 'PANASONIC KX-FT73CX',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '3125000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00007',
                'nama' => 'Penghancur Kertas',
                'tgl_perolehan' => '2014-12-15',
                'cabang_id' => '1',
                'penempatan_id' => '24',
                'spek' => 'Krisbow S333',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '715000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00008',
                'nama' => 'UPS',
                'tgl_perolehan' => '2013-12-20',
                'cabang_id' => '8',
                'penempatan_id' => '1',
                'spek' => 'ICA CT682B',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '4470000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00009',
                'nama' => 'UPS',
                'tgl_perolehan' => '2013-12-20',
                'cabang_id' => '8',
                'penempatan_id' => '1',
                'spek' => 'ICA 600VA',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '9749997',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00010',
                'nama' => 'Kursi Putar Pendek Berlengan',
                'tgl_perolehan' => '2014-02-21',
                'cabang_id' => '9',
                'penempatan_id' => '1',
                'spek' => 'Panel',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '3',
                'harga' => '500000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00011',
                'nama' => 'Meja 1/2 Biro',
                'tgl_perolehan' => '2014-02-21',
                'cabang_id' => '9',
                'penempatan_id' => '1',
                'spek' => 'Expo',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '3',
                'harga' => '1350000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00012',
                'nama' => 'Laptop',
                'tgl_perolehan' => '2016-06-25',
                'cabang_id' => '5',
                'penempatan_id' => '1',
                'spek' => 'Lenovo Ultrabook / Intel Core i7 / HDD 250 GB / RAM 8GB & Toshiba Tecra A5',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '4800000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00013',
                'nama' => 'Printer Inkjet',
                'tgl_perolehan' => '2015-07-27',
                'cabang_id' => '10',
                'penempatan_id' => '1',
                'spek' => 'Canon PIXMA 1P 1880, HP Deskjet 100, Epson TX-111',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '2250000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00014',
                'nama' => 'Printer Laser',
                'tgl_perolehan' => '2016-05-30',
                'cabang_id' => '5',
                'penempatan_id' => '1',
                'spek' => 'HP Laser Jet',
                'qty' => '5',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '1600000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00015',
                'nama' => 'Printer + Scanner',
                'tgl_perolehan' => '2019-03-12',
                'cabang_id' => '5',
                'penempatan_id' => '1',
                'spek' => 'Epson L3110',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '3',
                'harga' => '2250000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00016',
                'nama' => 'Lemari Arsip Besi',
                'tgl_perolehan' => '2014-03-30',
                'cabang_id' => '1',
                'penempatan_id' => '8',
                'spek' => 'Fiesta / 2 Pintu / Abu-abu',
                'qty' => '6',
                'umur_ekonomis_id' => '3',
                'kondisi_id' => '1',
                'harga' => '1220000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00017',
                'nama' => 'Kompor Gas',
                'tgl_perolehan' => '2013-12-30',
                'cabang_id' => '1',
                'penempatan_id' => '7',
                'spek' => '',
                'qty' => '1',
                'umur_ekonomis_id' => '3',
                'kondisi_id' => '2',
                'harga' => '900000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00018',
                'nama' => 'Papan Tulis',
                'tgl_perolehan' => '2014-12-10',
                'cabang_id' => '1',
                'penempatan_id' => '18',
                'spek' => 'Sakura',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '374000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00019',
                'nama' => 'Mesin Polisher',
                'tgl_perolehan' => '2008-12-17',
                'cabang_id' => '2',
                'penempatan_id' => '1',
                'spek' => 'Lux',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '14500000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00020',
                'nama' => 'Vacum Cleaner',
                'tgl_perolehan' => '2013-02-04',
                'cabang_id' => '2',
                'penempatan_id' => '1',
                'spek' => 'Krisbow',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '4200000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00021',
                'nama' => 'CPU',
                'tgl_perolehan' => '2016-06-25',
                'cabang_id' => '10',
                'penempatan_id' => '1',
                'spek' => 'Rakitan/ Intel Core i3 / HDD 500 GB / RAM 2 GB',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '5250000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00022',
                'nama' => 'Handy Talky (HT)',
                'tgl_perolehan' => '2014-05-30',
                'cabang_id' => '2',
                'penempatan_id' => '1',
                'spek' => 'HT Icom / VHF Transceiver / IC-V80',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '2175000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00023',
                'nama' => 'Lemari Kayu',
                'tgl_perolehan' => '2011-09-08',
                'cabang_id' => '5',
                'penempatan_id' => '1',
                'spek' => 'Uno',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '1530000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00024',
                'nama' => 'Dispenser Air',
                'tgl_perolehan' => '2016-02-29',
                'cabang_id' => '1',
                'penempatan_id' => '7',
                'spek' => 'Miyako',
                'qty' => '4',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '668000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00025',
                'nama' => 'Mouse',
                'tgl_perolehan' => '2013-01-30',
                'cabang_id' => '3',
                'penempatan_id' => '1',
                'spek' => 'HAVIT',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '4',
                'harga' => '150000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00026',
                'nama' => 'Printer Dotmatrix',
                'tgl_perolehan' => '2013-06-15',
                'cabang_id' => '1',
                'penempatan_id' => '22',
                'spek' => 'Printer Epson (dot matrix)',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '3',
                'harga' => '2750000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00027',
                'nama' => 'Televisi 32 Inci',
                'tgl_perolehan' => '2015-06-15',
                'cabang_id' => '1',
                'penempatan_id' => '16',
                'spek' => 'Krisbow',
                'qty' => '2',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '3269000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00028',
                'nama' => 'Stik Golf',
                'tgl_perolehan' => '2011-08-20',
                'cabang_id' => '1',
                'penempatan_id' => '8',
                'spek' => '',
                'qty' => '1',
                'umur_ekonomis_id' => '3',
                'kondisi_id' => '2',
                'harga' => '14400000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'kd_aset' => 'AST-00029',
                'nama' => 'Meja Pingpong',
                'tgl_perolehan' => '2013-02-04',
                'cabang_id' => '1',
                'penempatan_id' => '4',
                'spek' => '',
                'qty' => '1',
                'umur_ekonomis_id' => '2',
                'kondisi_id' => '2',
                'harga' => '1900000',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];


        tb_aset::insert($aset);

        // for ($i = 0; $i < 10; $i++) {
        //     tb_aset::factory()->count(1000)->create();
        // }
    }
}
